const xlsx = require('xlsx');
const PDFDocument = require('pdfkit');
const { Document, Packer, Paragraph, TextRun } = require('docx');

module.exports = async function handler(req, res) {
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "POST, OPTIONS");
  res.setHeader("Access-Control-Allow-Headers", "Content-Type");

  if (req.method === "OPTIONS") {
    return res.status(200).end();
  }

  try {
    const { message, mode } = req.body || {};
    const msgLower = (message || '').toLowerCase();

    // ==================== IMAGE GENERATION ====================
    if (mode === "image") {
      const imgRes = await fetch("https://api.openai.com/v1/images/generations", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${process.env.OPENAI_API_KEY}`
        },
        body: JSON.stringify({
          model: "gpt-4o-mini",   // or "dall-e-3" if you have access
          prompt: message,
          size: "1024x1024",
          n: 1
        })
      });

      const imgData = await imgRes.json();
      if (!imgData.data || !imgData.data[0]) {
        return res.status(500).json({ reply: "Image generation failed." });
      }

      return res.status(200).json({
        type: "image",
        image: imgData.data[0].url
      });
    }

    // ==================== EXCEL GENERATION ====================
    if (mode === "excel") {
      const workbook = xlsx.utils.book_new();
      const rows = [
        ["Employee", "Position", "Salary", "Department"],
        ["John Doe", "Manager", 8500, "Management"],
        ["Sarah Chen", "Developer", 7200, "Engineering"],
        ["Michael Smith", "Designer", 6500, "Design"],
        ["Emma Johnson", "HR", 5800, "Human Resources"],
        ["David Brown", "Sales", 6200, "Sales"],
        ["Sophia Lee", "Support", 4800, "Customer Service"]
      ];

      const worksheet = xlsx.utils.aoa_to_sheet(rows);
      xlsx.utils.book_append_sheet(workbook, worksheet, "Employees");

      const buffer = xlsx.write(workbook, { type: "buffer", bookType: "xlsx" });

      return res.status(200).json({
        type: "excel",
        data: buffer.toString("base64"),
        filename: "pay_scale.xlsx"
      });
    }

    // ==================== WORD DOCUMENT ====================
    if (msgLower.includes("word") || msgLower.includes("resume") || 
        msgLower.includes("cv") || msgLower.includes("letter")) {
      
      const doc = new Document({
        sections: [{
          properties: {},
          children: [
            new Paragraph({
              children: [new TextRun({ text: "Professional Document", size: 32, bold: true })]
            }),
            new Paragraph({
              children: [new TextRun({ text: message, size: 24 })]
            }),
            new Paragraph({
              children: [new TextRun({ text: "\nGenerated by OptimaSeek AI", size: 18 })]
            })
          ]
        }]
      });

      const buffer = await Packer.toBuffer(doc);

      return res.status(200).json({
        type: "word",
        data: buffer.toString("base64"),
        filename: "document.docx"
      });
    }

    // ==================== PDF DOCUMENT ====================
    if (msgLower.includes("pdf")) {
      const doc = new PDFDocument();
      let buffers = [];

      doc.on('data', chunk => buffers.push(chunk));
      doc.on('end', () => {
        const pdfData = Buffer.concat(buffers);
        res.status(200).json({
          type: "pdf",
          data: pdfData.toString('base64'),
          filename: "document.pdf"
        });
      });

      doc.fontSize(20).text("OptimaSeek AI - PDF Document", { align: 'center' });
      doc.moveDown();
      doc.fontSize(14).text(message);
      doc.end();
      return;
    }

    // ==================== NORMAL CHAT ====================
    const aiRes = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-api-key": process.env.ANTHROPIC_API_KEY,
        "anthropic-version": "2023-06-01"
      },
      body: JSON.stringify({
        model: "claude-3-haiku-20240307",
        max_tokens: 1024,
        messages: [{ role: "user", content: message }]
      })
    });

    const aiData = await aiRes.json();
    const reply = aiData.content?.[0]?.text || "Sorry, I couldn't process that.";

    return res.status(200).json({ reply });

  } catch (err) {
    console.error("Server Error:", err);
    return res.status(500).json({ reply: "Server error occurred. Please try again." });
  }
};