const xlsx = require('xlsx');
const PDFDocument = require('pdfkit');
const { Document, Packer, Paragraph, TextRun } = require('docx');

module.exports = async function handler(req, res) {

  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "POST, OPTIONS");
  res.setHeader("Access-Control-Allow-Headers", "Content-Type");

  if (req.method === "OPTIONS") {
    return res.status(200).end();
  }

  try {

    const { message, mode } = req.body;

    const msgLower = (message || '').toLowerCase();

    // =====================================================
    // IMAGE GENERATION
    // =====================================================

    if (mode === "image") {

      const imgRes = await fetch("https://api.openai.com/v1/images/generations", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${process.env.OPENAI_API_KEY}`
        },
        body: JSON.stringify({
          model: "gpt-image-1",
          prompt: message,
          size: "1024x1024"
        })
      });

      const imgData = await imgRes.json();

      if (!imgData.data || !imgData.data[0]) {
        return res.status(500).json({
          reply: "Image generation failed."
        });
      }

      return res.status(200).json({
        type: "image",
        image: imgData.data[0].url
      });
    }

    // =====================================================
    // EXCEL GENERATION
    // =====================================================

    if (mode === "excel") {

      const workbook = xlsx.utils.book_new();

      const rows = [
        ["Employee", "Position", "Salary"],
        ["John", "Manager", 7000],
        ["Sarah", "Developer", 5500],
        ["Michael", "Designer", 5000],
        ["Emma", "HR", 4500],
        ["David", "Sales", 4000],
        ["Sophia", "Support", 3800],
        ["Daniel", "Engineer", 6200],
        ["Olivia", "Marketing", 4800],
        ["James", "Finance", 5300],
        ["Ava", "Assistant", 3200]
      ];

      const worksheet = xlsx.utils.aoa_to_sheet(rows);

      xlsx.utils.book_append_sheet(workbook, worksheet, "Employees");

      const buffer = xlsx.write(workbook, {
        type: "buffer",
        bookType: "xlsx"
      });

      return res.status(200).json({
        type: "excel",
        data: buffer.toString("base64"),
        filename: "employees.xlsx"
      });
    }

    // =====================================================
    // WORD DOCUMENT
    // =====================================================

    const isWord =
      msgLower.includes('word') ||
      msgLower.includes('resume') ||
      msgLower.includes('cv') ||
      msgLower.includes('cover letter') ||
      msgLower.includes('contract');

    if (isWord) {

      const text = `Professional document created for:

${message}

Generated by OptimaSeek AI.`;

      const doc = new Document({
        sections: [
          {
            properties: {},
            children: [
              new Paragraph({
                children: [
                  new TextRun({
                    text,
                    size: 24
                  })
                ]
              })
            ]
          }
        ]
      });

      const buffer = await Packer.toBuffer(doc);

      return res.status(200).json({
        type: "word",
        data: buffer.toString("base64"),
        filename: "document.docx"
      });
    }

    // =====================================================
    // PDF FILE
    // =====================================================

    const isPdf = msgLower.includes('pdf');

    if (isPdf) {

      const doc = new PDFDocument();

      let buffers = [];

      doc.on('data', buffers.push.bind(buffers));

      doc.on('end', () => {

        const pdfData = Buffer.concat(buffers);

        return res.status(200).json({
          type: "pdf",
          data: pdfData.toString('base64'),
          filename: "document.pdf"
        });
      });

      doc.fontSize(16).text(`Generated PDF for:

${message}

Powered by OptimaSeek AI`, {
        align: 'left'
      });

      doc.end();

      return;
    }

    // =====================================================
    // NORMAL CHAT
    // =====================================================

    const aiRes = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-api-key": process.env.ANTHROPIC_API_KEY,
        "anthropic-version": "2023-06-01"
      },
      body: JSON.stringify({
        model: "claude-3-haiku-20240307",
        max_tokens: 1024,
        messages: [
          {
            role: "user",
            content: message
          }
        ]
      })
    });

    const aiData = await aiRes.json();

    const reply =
      aiData.content &&
      aiData.content[0] &&
      aiData.content[0].text
        ? aiData.content[0].text
        : "No response.";

    return res.status(200).json({
      reply
    });

  } catch (err) {

    console.error("SERVER ERROR:", err);

    return res.status(500).json({
      reply: err.message || "Server error"
    });
  }
}
